### 變數設定
@baseUrl = http://localhost:8081/api/booking-orders
@authUrl = http://localhost:8081/api/auth
@orderId = 31

### 0. 登入獲取 JWT Token
# @name login
POST {{authUrl}}/login
Content-Type: application/json

{
  "username": "admin01",
  "password": "123456"
}

### 自動綁定 Token 變數
@jwtToken = {{login.response.body.token}}

### --------------------------------------------------------

### 1. GET 查詢所有預訂主訂單
GET {{baseUrl}}
Authorization: Bearer {{jwtToken}}

### 2. 依預訂訂單編號查詢 (例如：bookingOrderId = 1)
GET {{baseUrl}}?bookingOrderId=1
Authorization: Bearer {{jwtToken}}

### 3. 依會員編號查詢 (例如：memberId = 2)
GET {{baseUrl}}?memberId=12
Authorization: Bearer {{jwtToken}}

### 4. POST 新增預訂主訂單
POST {{baseUrl}}
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "memberId": 1,
  "orderStatus": "待付款",
  "paymentId": 2
}

### 5. PUT 修改預訂主訂單資訊 (修改 ID = {{orderId}} 的資料)
PUT {{baseUrl}}/{{orderId}}
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "memberId": 1,
  "orderStatus": "訂單完成",
  "paymentId": 2
}

### 6. DELETE 刪除預訂主訂單 (刪除 ID = {{orderId}} 的資料)
DELETE {{baseUrl}}/{{orderId}}
Authorization: Bearer {{jwtToken}}