### 變數設定
@baseUrl = http://localhost:8081/api/booking-orders
@auth = Basic vic1 111
@orderId = 55

### 1. GET 查詢所有預訂主訂單
GET {{baseUrl}}
Authorization: {{auth}}

### 2. 依預訂訂單編號查詢 (例如：bookingOrderId = 1)
GET {{baseUrl}}?bookingOrderId=45
Authorization: {{auth}}

### 3. 依會員編號查詢 (例如：memberId = 2)
GET {{baseUrl}}?memberId=2
Authorization: {{auth}}

### 4. 依預訂狀態查詢 (例如：1)
GET {{baseUrl}}?orderStatus=待付款
Authorization: {{auth}}

# ### 5. GET 查詢單一預訂主訂單 (依路徑變數)
# GET {{baseUrl}}/{{orderId}}
# Authorization: {{auth}}

### 6. POST 新增預訂主訂單
POST {{baseUrl}}
Authorization: {{auth}}
Content-Type: application/json

{
  "memberId": 1,
  "bookingTotalPrice": 3500,
  "orderStatus": "付款取消",
  "paymentId": 2
}

### 7. PUT 修改預訂主訂單資訊 (修改 ID = 1 的資料)
PUT {{baseUrl}}/{{orderId}}
Authorization: {{auth}}
Content-Type: application/json

{
  "memberId": 1,
  "bookingTotalPrice": 4200,
  "orderStatus": "訂單取消",
  "paymentId": 2
}

# ### 8. PATCH 快速更新預訂狀態 (將 ID = 1 的狀態改為 3)
# PATCH {{baseUrl}}/{{orderId}}/status
# Authorization: {{auth}}
# Content-Type: application/json

# {
#   "orderStatus": "3"
# }

### 9. DELETE 刪除預訂主訂單 (刪除 ID = 1 的資料)
DELETE {{baseUrl}}/{{orderId}}
Authorization: {{auth}}